//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/MyInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/MyInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MyInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MyInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInputActions"",
    ""maps"": [
        {
            ""name"": ""XRControl"",
            ""id"": ""371e0814-5a1e-4165-ab0d-913601ad518b"",
            ""actions"": [
                {
                    ""name"": ""joystickAction"",
                    ""type"": ""Value"",
                    ""id"": ""11272c5a-6e08-48e0-83e4-cdbf01564d01"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""triggerAction"",
                    ""type"": ""Value"",
                    ""id"": ""444b0838-0864-450f-bf32-e0b2cfa430c1"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""nextJointButton"",
                    ""type"": ""Button"",
                    ""id"": ""4b1993b7-fd4f-4a3c-9d25-d451038fc102"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""prevJointButton"",
                    ""type"": ""Button"",
                    ""id"": ""0ea50755-aaed-4a8f-933e-9ff1d840bccb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""resetPoseButton"",
                    ""type"": ""Button"",
                    ""id"": ""59cecf38-5b64-47ef-a45b-927efec3524e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""658af896-7f7c-462a-bfce-495675fdee16"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joystickAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""374bdc65-b301-46bf-ae15-a82d247d9726"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joystickAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efde0a4c-b406-49f1-9c23-28562279f2a8"",
                    ""path"": ""<XRController>{LeftHand}/triggerSlide"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e33aef75-c137-46d9-96c1-ee9687d7a7a9"",
                    ""path"": ""<XRController>{RightHand}/triggerSlide"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4746c9b-03e6-43cd-9292-88bc6001b903"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""nextJointButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd543cb7-8d33-458b-9349-76ed63baaabd"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""nextJointButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aea3135a-a53d-4f9b-bc36-15f12e4900d1"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""prevJointButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0453c1f5-050e-48e4-b9d1-0d2983abf510"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""prevJointButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bda896ea-c6d1-41b6-b614-38d669242215"",
                    ""path"": ""<XRController>{LeftHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""resetPoseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4b8d0d5-1417-4e2a-85c4-1d06645d13d7"",
                    ""path"": ""<XRController>{RightHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""resetPoseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // XRControl
        m_XRControl = asset.FindActionMap("XRControl", throwIfNotFound: true);
        m_XRControl_joystickAction = m_XRControl.FindAction("joystickAction", throwIfNotFound: true);
        m_XRControl_triggerAction = m_XRControl.FindAction("triggerAction", throwIfNotFound: true);
        m_XRControl_nextJointButton = m_XRControl.FindAction("nextJointButton", throwIfNotFound: true);
        m_XRControl_prevJointButton = m_XRControl.FindAction("prevJointButton", throwIfNotFound: true);
        m_XRControl_resetPoseButton = m_XRControl.FindAction("resetPoseButton", throwIfNotFound: true);
    }

    ~@MyInputActions()
    {
        UnityEngine.Debug.Assert(!m_XRControl.enabled, "This will cause a leak and performance issues, MyInputActions.XRControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // XRControl
    private readonly InputActionMap m_XRControl;
    private List<IXRControlActions> m_XRControlActionsCallbackInterfaces = new List<IXRControlActions>();
    private readonly InputAction m_XRControl_joystickAction;
    private readonly InputAction m_XRControl_triggerAction;
    private readonly InputAction m_XRControl_nextJointButton;
    private readonly InputAction m_XRControl_prevJointButton;
    private readonly InputAction m_XRControl_resetPoseButton;
    /// <summary>
    /// Provides access to input actions defined in input action map "XRControl".
    /// </summary>
    public struct XRControlActions
    {
        private @MyInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public XRControlActions(@MyInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "XRControl/joystickAction".
        /// </summary>
        public InputAction @joystickAction => m_Wrapper.m_XRControl_joystickAction;
        /// <summary>
        /// Provides access to the underlying input action "XRControl/triggerAction".
        /// </summary>
        public InputAction @triggerAction => m_Wrapper.m_XRControl_triggerAction;
        /// <summary>
        /// Provides access to the underlying input action "XRControl/nextJointButton".
        /// </summary>
        public InputAction @nextJointButton => m_Wrapper.m_XRControl_nextJointButton;
        /// <summary>
        /// Provides access to the underlying input action "XRControl/prevJointButton".
        /// </summary>
        public InputAction @prevJointButton => m_Wrapper.m_XRControl_prevJointButton;
        /// <summary>
        /// Provides access to the underlying input action "XRControl/resetPoseButton".
        /// </summary>
        public InputAction @resetPoseButton => m_Wrapper.m_XRControl_resetPoseButton;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_XRControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="XRControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(XRControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="XRControlActions" />
        public void AddCallbacks(IXRControlActions instance)
        {
            if (instance == null || m_Wrapper.m_XRControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRControlActionsCallbackInterfaces.Add(instance);
            @joystickAction.started += instance.OnJoystickAction;
            @joystickAction.performed += instance.OnJoystickAction;
            @joystickAction.canceled += instance.OnJoystickAction;
            @triggerAction.started += instance.OnTriggerAction;
            @triggerAction.performed += instance.OnTriggerAction;
            @triggerAction.canceled += instance.OnTriggerAction;
            @nextJointButton.started += instance.OnNextJointButton;
            @nextJointButton.performed += instance.OnNextJointButton;
            @nextJointButton.canceled += instance.OnNextJointButton;
            @prevJointButton.started += instance.OnPrevJointButton;
            @prevJointButton.performed += instance.OnPrevJointButton;
            @prevJointButton.canceled += instance.OnPrevJointButton;
            @resetPoseButton.started += instance.OnResetPoseButton;
            @resetPoseButton.performed += instance.OnResetPoseButton;
            @resetPoseButton.canceled += instance.OnResetPoseButton;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="XRControlActions" />
        private void UnregisterCallbacks(IXRControlActions instance)
        {
            @joystickAction.started -= instance.OnJoystickAction;
            @joystickAction.performed -= instance.OnJoystickAction;
            @joystickAction.canceled -= instance.OnJoystickAction;
            @triggerAction.started -= instance.OnTriggerAction;
            @triggerAction.performed -= instance.OnTriggerAction;
            @triggerAction.canceled -= instance.OnTriggerAction;
            @nextJointButton.started -= instance.OnNextJointButton;
            @nextJointButton.performed -= instance.OnNextJointButton;
            @nextJointButton.canceled -= instance.OnNextJointButton;
            @prevJointButton.started -= instance.OnPrevJointButton;
            @prevJointButton.performed -= instance.OnPrevJointButton;
            @prevJointButton.canceled -= instance.OnPrevJointButton;
            @resetPoseButton.started -= instance.OnResetPoseButton;
            @resetPoseButton.performed -= instance.OnResetPoseButton;
            @resetPoseButton.canceled -= instance.OnResetPoseButton;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="XRControlActions.UnregisterCallbacks(IXRControlActions)" />.
        /// </summary>
        /// <seealso cref="XRControlActions.UnregisterCallbacks(IXRControlActions)" />
        public void RemoveCallbacks(IXRControlActions instance)
        {
            if (m_Wrapper.m_XRControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="XRControlActions.AddCallbacks(IXRControlActions)" />
        /// <seealso cref="XRControlActions.RemoveCallbacks(IXRControlActions)" />
        /// <seealso cref="XRControlActions.UnregisterCallbacks(IXRControlActions)" />
        public void SetCallbacks(IXRControlActions instance)
        {
            foreach (var item in m_Wrapper.m_XRControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="XRControlActions" /> instance referencing this action map.
    /// </summary>
    public XRControlActions @XRControl => new XRControlActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "XRControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="XRControlActions.AddCallbacks(IXRControlActions)" />
    /// <seealso cref="XRControlActions.RemoveCallbacks(IXRControlActions)" />
    public interface IXRControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "joystickAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJoystickAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "triggerAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "nextJointButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextJointButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "prevJointButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrevJointButton(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "resetPoseButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResetPoseButton(InputAction.CallbackContext context);
    }
}
